language: java
script:
- ./gradlew build --info --stacktrace
- rm build/libs/*unoptimised* # get outta here! we dont want the big useless jar on github releases lol
deploy:
  provider: releases
  api_key:
    secure: KCWI8QKAz2Hq0xqy0EXhY+fJwnE57cBQN54xRG0yB9ddtj33juO1/LyyrTarSLvF5TRST0eQLekGxdXYZnw+bAHgl2lj8HxlrpkpfC+FO9aNn0FCPA53QIpE8pCb5cUlBe9uvTE2rdgbi6yyBEMptWM2gMAQYJ4++sUX5SVHVGX+ZVmDezWeNuw5URxjf6Y0BeEq7Er0yidcop0IPBSIksqNLhTTQ75Z16UHAeqMf7iU8pKELen1cIpHYlk/qN67PMjW+weXv4U8DzSfXF2ORoJkkkJ8zqzu5wWrVzgtVyvELqghnW03WSEoSMYeW+J/818dV37yo40ht8pHrDbY/EJdXJh5fYpv/r5l3Hny4EzOLqDOmQ03cgKlaOxLakyJvKiyxrfrvMs92Id2EbTe5LpYEAdQ7bNW/JUgqmOykhDbUd9xL+86I0f6FXQTGgKrsq/w3yajYVRX+zDY0CzqLqQD7HHl3FtOac0hFCQlxkbJjptUXdXELlTbJKh6XJrv3iLjeoNZs6KF6VIq1f+Hyjps3kvIE7Rczoko8BJAdrdYBaL/FzWMqYFxZD2qD3/DTsAfY6X8W8mkina6F3x6RC5SWQ4KtjJmNupvAOHeXaBcMbX5N7/kM08bm27CVr+Ptfdz75epyvA6CulzyrWjPdmUtaZylNIymcKxqki3Wic=
  all_branches: true
  file_glob: true
  file:
  - build/libs/*
  - build/launch4j/*
  skip_cleanup: true
  on:
    tags: true
    repo: ImpactDevelopment/Installer
